### ISSUE TITLE
Generated an exception while executing task

### ISSUE THREAD

**Issue by eldediamante** [Ajneb97/PlayerTimeLimit#5]
Hello!
I have a spigot server and I get this error, I only changed the color and segmentation of the bar.

>[20:06:27] [Craft Scheduler Thread - 96/WARN]: [PlayerTimeLimit] Plugin PlayerTimeLimit v1.6.1 generated an exception while executing task 16930
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at ptl.ajneb97.utils.UtilsTime.getNextResetMillis(UtilsTime.java:48) ~[?:?]
        at ptl.ajneb97.managers.ServerManager.saveDataTime(ServerManager.java:33) ~[?:?]
        at ptl.ajneb97.tasks.DataSaveTask.execute(DataSaveTask.java:38) ~[?:?]
        at ptl.ajneb97.tasks.DataSaveTask$1.run(DataSaveTask.java:29) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Ajneb97** [comment]
Send me your config please

**Comment by eldediamante** [comment]
https://drive.google.com/file/d/1GtmX3HfdBaWFVp0RbLhoA3gSlJWORELz/view?usp=sharing

**Comment by Ajneb97** [comment]
reset_time: 0:00
set it to
reset_time: "0:00"

**Comment by eldediamante** [comment]
oh, okey, thanks

**Comment by eldediamante** [comment]
The error no longer pops up, thank you very much
